/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import java.util.*;
import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class AParaPassoComando extends PComando
{
    private PVar _var_;
    private TNumeroInt _aDe_;
    private TNumeroInt _aPasso_;
    private TNumeroInt _aAte_;
    private final LinkedList<PComando> _comando_ = new LinkedList<PComando>();

    public AParaPassoComando()
    {
        // Constructor
    }

    public AParaPassoComando(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TNumeroInt _aDe_,
        @SuppressWarnings("hiding") TNumeroInt _aPasso_,
        @SuppressWarnings("hiding") TNumeroInt _aAte_,
        @SuppressWarnings("hiding") List<?> _comando_)
    {
        // Constructor
        setVar(_var_);

        setADe(_aDe_);

        setAPasso(_aPasso_);

        setAAte(_aAte_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AParaPassoComando(
            cloneNode(this._var_),
            cloneNode(this._aDe_),
            cloneNode(this._aPasso_),
            cloneNode(this._aAte_),
            cloneList(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaPassoComando(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TNumeroInt getADe()
    {
        return this._aDe_;
    }

    public void setADe(TNumeroInt node)
    {
        if(this._aDe_ != null)
        {
            this._aDe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aDe_ = node;
    }

    public TNumeroInt getAPasso()
    {
        return this._aPasso_;
    }

    public void setAPasso(TNumeroInt node)
    {
        if(this._aPasso_ != null)
        {
            this._aPasso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aPasso_ = node;
    }

    public TNumeroInt getAAte()
    {
        return this._aAte_;
    }

    public void setAAte(TNumeroInt node)
    {
        if(this._aAte_ != null)
        {
            this._aAte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aAte_ = node;
    }

    public LinkedList<PComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<?> list)
    {
        for(PComando e : this._comando_)
        {
            e.parent(null);
        }
        this._comando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comando_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._aDe_)
            + toString(this._aPasso_)
            + toString(this._aAte_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._aDe_ == child)
        {
            this._aDe_ = null;
            return;
        }

        if(this._aPasso_ == child)
        {
            this._aPasso_ = null;
            return;
        }

        if(this._aAte_ == child)
        {
            this._aAte_ = null;
            return;
        }

        if(this._comando_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._aDe_ == oldChild)
        {
            setADe((TNumeroInt) newChild);
            return;
        }

        if(this._aPasso_ == oldChild)
        {
            setAPasso((TNumeroInt) newChild);
            return;
        }

        if(this._aAte_ == oldChild)
        {
            setAAte((TNumeroInt) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
