/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class AScharString extends PString
{
    private TCaracter _caracter_;

    public AScharString()
    {
        // Constructor
    }

    public AScharString(
        @SuppressWarnings("hiding") TCaracter _caracter_)
    {
        // Constructor
        setCaracter(_caracter_);

    }

    @Override
    public Object clone()
    {
        return new AScharString(
            cloneNode(this._caracter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAScharString(this);
    }

    public TCaracter getCaracter()
    {
        return this._caracter_;
    }

    public void setCaracter(TCaracter node)
    {
        if(this._caracter_ != null)
        {
            this._caracter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caracter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caracter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caracter_ == child)
        {
            this._caracter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caracter_ == oldChild)
        {
            setCaracter((TCaracter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
