/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import java.util.*;
import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class ASenaoComando extends PSenaoComando
{
    private TSenao _senao_;
    private final LinkedList<PComandoRepeat> _comandoRepeat_ = new LinkedList<PComandoRepeat>();

    public ASenaoComando()
    {
        // Constructor
    }

    public ASenaoComando(
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") List<?> _comandoRepeat_)
    {
        // Constructor
        setSenao(_senao_);

        setComandoRepeat(_comandoRepeat_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoComando(
            cloneNode(this._senao_),
            cloneList(this._comandoRepeat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoComando(this);
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public LinkedList<PComandoRepeat> getComandoRepeat()
    {
        return this._comandoRepeat_;
    }

    public void setComandoRepeat(List<?> list)
    {
        for(PComandoRepeat e : this._comandoRepeat_)
        {
            e.parent(null);
        }
        this._comandoRepeat_.clear();

        for(Object obj_e : list)
        {
            PComandoRepeat e = (PComandoRepeat) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoRepeat_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senao_)
            + toString(this._comandoRepeat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._comandoRepeat_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        for(ListIterator<PComandoRepeat> i = this._comandoRepeat_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoRepeat) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
