/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class TAleatorio extends Token
{
    public TAleatorio()
    {
        super.setText("aleatorio");
    }

    public TAleatorio(int line, int pos)
    {
        super.setText("aleatorio");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAleatorio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAleatorio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAleatorio text.");
    }
}
