/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class TAlgoritmo extends Token
{
    public TAlgoritmo()
    {
        super.setText("algoritmo");
    }

    public TAlgoritmo(int line, int pos)
    {
        super.setText("algoritmo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlgoritmo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlgoritmo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlgoritmo text.");
    }
}
