/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.node;

import compiladorLFT.analysis.*;

@SuppressWarnings("nls")
public final class TArquivo extends Token
{
    public TArquivo()
    {
        super.setText("arquivo");
    }

    public TArquivo(int line, int pos)
    {
        super.setText("arquivo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArquivo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArquivo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArquivo text.");
    }
}
