/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.lexer;

import java.io.*;
import compiladorLFT.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 0: state = State.NORMAL; break;
                            }
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                                case 0: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMMENT; break;
                            }
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontosFinais(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimAlgoritmo(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPara(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogico(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepita(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRetorne(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdadeiro(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXou(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAleatorio(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAlgoritmo(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArquivo(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasDuplas(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAspasSimples(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAte(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaracter(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteD(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColcheteE(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDe(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDividido(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoisPontos(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscolha(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreval(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimEnquanto(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimFuncao(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimProcedimento(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimRepita(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimSe(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimVar(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimAvalie(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentificador(text, line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumero(text, line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorIgual(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMais(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseD(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParenteseE(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPasso(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPausa(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRecebe(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TResto(line, pos); }
    Token new70(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVezes(line, pos); }
    Token new72(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroInt(text, line, pos); }
    Token new73(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroReal(text, line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVarStr(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new77(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioSimples(text, line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(line, pos); }
    Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCommentEnd(line, pos); }
    Token new80(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCommentBody(text, line, pos); }
    Token new81(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new82(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new83(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimTexto(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 1}, {34, 34, 6}, {35, 36, 1}, {37, 37, 7}, {38, 38, 1}, {39, 39, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {63, 64, 1}, {65, 90, 23}, {91, 91, 24}, {92, 92, 1}, {93, 93, 25}, {94, 94, 1}, {95, 95, 26}, {96, 96, 1}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 30}, {101, 101, 31}, {102, 102, 32}, {103, 104, 28}, {105, 105, 33}, {106, 107, 28}, {108, 108, 34}, {109, 109, 28}, {110, 110, 35}, {111, 111, 36}, {112, 112, 37}, {113, 113, 28}, {114, 114, 38}, {115, 115, 39}, {116, 117, 28}, {118, 118, 40}, {119, 119, 28}, {120, 120, 41}, {121, 122, 28}, {123, 65535, 1}, },
            {{0, 9, 1}, {11, 12, 1}, {14, 65535, 1}, },
            {{0, 65535, -3}, },
            {},
            {{10, 10, 42}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 12, -3}, {14, 45, 1}, {46, 46, 43}, {47, 65535, 1}, },
            {{0, 12, -3}, {14, 41, 1}, {42, 42, 44}, {43, 46, 1}, {47, 47, 45}, {48, 65535, 1}, },
            {{0, 45, -17}, {46, 46, 46}, {47, 47, 1}, {48, 57, 47}, {58, 64, 1}, {65, 90, 48}, {91, 94, 1}, {95, 95, 49}, {96, 96, 1}, {97, 122, 50}, {123, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 12, -3}, {14, 44, 1}, {45, 45, 51}, {46, 60, 1}, {61, 61, 52}, {62, 62, 53}, {63, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 12, -3}, {14, 60, 1}, {61, 61, 54}, {62, 65535, 1}, },
            {{0, 12, -3}, {14, 47, 1}, {48, 57, 55}, {58, 64, 1}, {65, 90, 23}, {91, 96, -19}, {97, 122, 28}, {123, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 47, -25}, {48, 57, 56}, {58, 64, 1}, {65, 90, 57}, {91, 94, 1}, {95, 95, 58}, {96, 96, 1}, {97, 122, 59}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 107, 28}, {108, 108, 60}, {109, 113, 28}, {114, 114, 61}, {115, 115, 28}, {116, 116, 62}, {117, 117, 28}, {118, 118, 63}, {119, 122, 28}, {123, 65535, 1}, },
            {{0, 65535, -25}, },
            {{0, 96, -25}, {97, 97, 64}, {98, 110, 28}, {111, 111, 65}, {112, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 100, 28}, {101, 101, 66}, {102, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 109, 28}, {110, 110, 67}, {111, 114, 28}, {115, 115, 68}, {116, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 97, 69}, {98, 104, 28}, {105, 105, 70}, {106, 116, 28}, {117, 117, 71}, {118, 122, 28}, {123, 65535, 1}, },
            {{0, 109, -33}, {110, 110, 72}, {111, 122, 28}, {123, 65535, 1}, },
            {{0, 100, -32}, {101, 101, 73}, {102, 110, 28}, {111, 111, 74}, {112, 65535, -31}, },
            {{0, 96, -25}, {97, 97, 75}, {98, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 116, 28}, {117, 117, 76}, {118, 65535, -34}, },
            {{0, 96, -25}, {97, 97, 77}, {98, 113, 28}, {114, 114, 78}, {115, 122, 28}, {123, 65535, 1}, },
            {{0, 100, -32}, {101, 101, 79}, {102, 65535, -32}, },
            {{0, 100, -32}, {101, 101, 80}, {102, 65535, -32}, },
            {{0, 96, -25}, {97, 97, 81}, {98, 100, 28}, {101, 101, 82}, {102, 65535, -32}, },
            {{0, 96, -25}, {97, 110, 28}, {111, 111, 83}, {112, 65535, -31}, },
            {},
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 9, 84}, {10, 10, 85}, {11, 12, 84}, {13, 13, 86}, {14, 65535, 84}, },
            {{0, 47, -25}, {48, 57, 87}, {58, 65535, 1}, },
            {{0, 65535, -19}, },
            {{0, 64, -25}, {65, 65535, -19}, },
            {{0, 65535, -50}, },
            {{0, 65535, -50}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -3}, },
            {{0, 65535, -50}, },
            {{0, 65535, -28}, },
            {{0, 65535, -28}, },
            {{0, 65535, -28}, },
            {{0, 65535, -28}, },
            {{0, 100, -32}, {101, 101, 88}, {102, 102, 28}, {103, 103, 89}, {104, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 112, 28}, {113, 113, 90}, {114, 122, 28}, {123, 65535, 1}, },
            {{0, 100, -32}, {101, 101, 91}, {102, 65535, -32}, },
            {{0, 96, -25}, {97, 97, 92}, {98, 65535, -37}, },
            {{0, 96, -25}, {97, 113, 28}, {114, 114, 93}, {115, 115, 94}, {116, 65535, -33}, },
            {{0, 109, -33}, {110, 110, 95}, {111, 65535, -35}, },
            {{0, 65535, -25}, },
            {{0, 112, -63}, {113, 113, 96}, {114, 115, 28}, {116, 116, 97}, {117, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 98, 28}, {99, 99, 98}, {100, 122, 28}, {123, 65535, 1}, },
            {{0, 98, -70}, {99, 99, 99}, {100, 107, 28}, {108, 108, 100}, {109, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 108, 28}, {109, 109, 101}, {110, 122, 28}, {123, 65535, 1}, },
            {{0, 109, -33}, {110, 110, 102}, {111, 65535, -35}, },
            {{0, 96, -25}, {97, 104, 28}, {105, 105, 103}, {106, 115, 28}, {116, 116, 104}, {117, 65535, -69}, },
            {{0, 104, -74}, {105, 105, 105}, {106, 122, 28}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 102, 28}, {103, 103, 106}, {104, 65535, -62}, },
            {{0, 110, -43}, {111, 111, 107}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 113, -66}, {114, 114, 108}, {115, 115, 109}, {116, 116, 28}, {117, 117, 110}, {118, 65535, -34}, },
            {{0, 110, -43}, {111, 111, 111}, {112, 65535, -31}, },
            {{0, 96, -25}, {97, 97, 112}, {98, 111, 28}, {112, 112, 113}, {113, 115, 28}, {116, 116, 114}, {117, 65535, -69}, },
            {{0, 109, -33}, {110, 110, 115}, {111, 65535, -35}, },
            {{0, 113, -66}, {114, 114, 116}, {115, 65535, -39}, },
            {{0, 113, -66}, {114, 114, 117}, {115, 65535, -39}, },
            {{0, 113, -66}, {114, 114, 118}, {115, 116, 28}, {117, 117, 119}, {118, 65535, -34}, },
            {{0, 65535, -47}, },
            {},
            {{10, 10, 120}, },
            {{0, 47, -25}, {48, 57, 121}, {58, 65535, 1}, },
            {{0, 96, -25}, {97, 97, 122}, {98, 65535, -37}, },
            {{0, 110, -43}, {111, 111, 123}, {112, 65535, -31}, },
            {{0, 116, -38}, {117, 117, 124}, {118, 65535, -34}, },
            {{0, 65535, -25}, },
            {{0, 107, -29}, {108, 108, 125}, {109, 65535, -71}, },
            {{0, 96, -25}, {97, 97, 126}, {98, 65535, -37}, },
            {{0, 110, -43}, {111, 111, 127}, {112, 65535, -31}, },
            {{0, 96, -25}, {97, 114, 28}, {115, 115, 128}, {116, 65535, -33}, },
            {{0, 116, -38}, {117, 117, 129}, {118, 65535, -34}, },
            {{0, 96, -25}, {97, 97, 130}, {98, 65535, -37}, },
            {{0, 110, -43}, {111, 111, 131}, {112, 113, 28}, {114, 114, 132}, {115, 65535, -39}, },
            {{0, 96, -25}, {97, 97, 133}, {98, 65535, -37}, },
            {{0, 114, -97}, {115, 115, 134}, {116, 65535, -33}, },
            {{0, 12, -3}, {14, 31, 1}, {32, 32, 135}, {33, 45, 1}, {46, 46, 136}, {47, 47, 1}, {48, 65535, -25}, },
            {{0, 98, -70}, {99, 99, 137}, {100, 65535, -70}, },
            {{0, 98, -70}, {99, 99, 138}, {100, 65535, -70}, },
            {{0, 100, -32}, {101, 101, 139}, {102, 65535, -32}, },
            {{0, 96, -25}, {97, 97, 140}, {98, 65535, -37}, },
            {{0, 104, -74}, {105, 105, 141}, {106, 65535, -75}, },
            {{0, 65535, -25}, },
            {{0, 96, -25}, {97, 97, 142}, {98, 65535, -37}, },
            {{0, 114, -97}, {115, 115, 143}, {116, 65535, -33}, },
            {{0, 114, -97}, {115, 115, 144}, {116, 65535, -33}, },
            {{0, 98, -70}, {99, 99, 145}, {100, 102, 28}, {103, 103, 146}, {104, 65535, -62}, },
            {{0, 107, -29}, {108, 108, 147}, {109, 65535, -71}, },
            {{0, 104, -74}, {105, 105, 148}, {106, 65535, -75}, },
            {{0, 110, -43}, {111, 111, 149}, {112, 65535, -31}, },
            {{0, 96, -25}, {97, 97, 150}, {98, 65535, -37}, },
            {{0, 94, -25}, {95, 95, 151}, {96, 65535, -25}, },
            {{0, 96, -25}, {97, 99, 28}, {100, 100, 152}, {101, 122, 28}, {123, 65535, 1}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {},
            {{0, 65535, -89}, },
            {{0, 96, -25}, {97, 115, 28}, {116, 116, 153}, {117, 65535, -69}, },
            {{0, 113, -66}, {114, 114, 154}, {115, 65535, -39}, },
            {{0, 104, -74}, {105, 105, 155}, {106, 65535, -75}, },
            {{0, 104, -74}, {105, 105, 156}, {106, 65535, -75}, },
            {{0, 98, -70}, {99, 99, 157}, {100, 65535, -70}, },
            {{0, 65535, -25}, },
            {{0, 115, -124}, {116, 116, 158}, {117, 65535, -69}, },
            {{0, 96, -25}, {97, 97, 159}, {98, 65535, -37}, },
            {{0, 110, -43}, {111, 111, 160}, {112, 65535, -31}, },
            {{0, 107, -29}, {108, 108, 161}, {109, 65535, -71}, },
            {{0, 100, -32}, {101, 101, 162}, {102, 65535, -32}, },
            {{0, 65535, -25}, },
            {{0, 110, -43}, {111, 111, 163}, {112, 65535, -31}, },
            {{0, 12, -3}, {14, 96, 1}, {97, 97, 164}, {98, 100, 1}, {101, 101, 165}, {102, 102, 166}, {103, 111, 1}, {112, 112, 167}, {113, 113, 1}, {114, 114, 168}, {115, 115, 169}, {116, 117, 1}, {118, 118, 170}, {119, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 96, -25}, {97, 97, 171}, {98, 65535, -37}, },
            {{0, 104, -74}, {105, 105, 172}, {106, 65535, -75}, },
            {{0, 104, -74}, {105, 105, 173}, {106, 65535, -75}, },
            {{0, 65535, -25}, },
            {{0, 98, -70}, {99, 99, 174}, {100, 65535, -70}, },
            {{0, 65535, -25}, },
            {{0, 110, -43}, {111, 111, 175}, {112, 65535, -31}, },
            {{0, 96, -25}, {97, 97, 176}, {98, 65535, -37}, },
            {{0, 100, -32}, {101, 101, 177}, {102, 65535, -32}, },
            {{0, 113, -66}, {114, 114, 178}, {115, 65535, -39}, },
            {{0, 65535, -25}, },
            {{0, 115, -124}, {116, 116, 179}, {117, 65535, -69}, },
            {{0, 113, -66}, {114, 114, 180}, {115, 65535, -39}, },
            {{0, 110, -43}, {111, 111, 181}, {112, 65535, -31}, },
            {{0, 96, -50}, {97, 114, 50}, {115, 115, 182}, {116, 122, 50}, {123, 65535, 1}, },
            {{0, 96, -25}, {97, 97, 183}, {98, 65535, -37}, },
            {{0, 110, -43}, {111, 111, 184}, {112, 65535, -31}, },
            {{0, 104, -74}, {105, 105, 185}, {106, 65535, -75}, },
            {{0, 96, -25}, {97, 117, 28}, {118, 118, 186}, {119, 65535, -29}, },
            {{0, 100, -32}, {101, 101, 187}, {102, 65535, -32}, },
            {{0, 115, -124}, {116, 116, 188}, {117, 65535, -69}, },
            {{0, 65535, -25}, },
            {{0, 109, -33}, {110, 110, 189}, {111, 65535, -35}, },
            {{0, 65535, -25}, },
            {{0, 96, -25}, {97, 103, 28}, {104, 104, 190}, {105, 122, 28}, {123, 65535, 1}, },
            {{0, 117, -157}, {118, 118, 191}, {119, 65535, -29}, },
            {{0, 65535, -25}, },
            {{0, 12, -3}, {14, 107, 1}, {108, 108, 192}, {109, 117, 1}, {118, 118, 193}, {119, 65535, 1}, },
            {{0, 12, -3}, {14, 109, 1}, {110, 110, 194}, {111, 65535, 1}, },
            {{0, 12, -3}, {14, 116, 1}, {117, 117, 195}, {118, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 196}, {98, 113, 1}, {114, 114, 197}, {115, 65535, 1}, },
            {{0, 12, -3}, {14, 100, 1}, {101, 101, 198}, {102, 65535, 1}, },
            {{0, 100, -170}, {101, 101, 199}, {102, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 200}, {98, 65535, 1}, },
            {{0, 110, -43}, {111, 111, 201}, {112, 65535, -31}, },
            {{0, 110, -43}, {111, 111, 202}, {112, 65535, -31}, },
            {{0, 113, -66}, {114, 114, 203}, {115, 65535, -39}, },
            {{0, 110, -43}, {111, 111, 204}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {{0, 99, -119}, {100, 100, 205}, {101, 65535, -119}, },
            {{0, 96, -25}, {97, 97, 206}, {98, 65535, -37}, },
            {{0, 96, -25}, {97, 97, 207}, {98, 65535, -37}, },
            {{0, 109, -33}, {110, 110, 208}, {111, 65535, -35}, },
            {{0, 65535, -25}, },
            {{0, 96, -50}, {97, 115, 50}, {116, 116, 209}, {117, 122, 50}, {123, 65535, 1}, },
            {{0, 99, -119}, {100, 100, 210}, {101, 65535, -119}, },
            {{0, 113, -66}, {114, 114, 211}, {115, 65535, -39}, },
            {{0, 115, -124}, {116, 116, 212}, {117, 65535, -69}, },
            {{0, 110, -43}, {111, 111, 213}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 100, -32}, {101, 101, 214}, {102, 65535, -32}, },
            {{0, 115, -124}, {116, 116, 215}, {117, 65535, -69}, },
            {{0, 96, -25}, {97, 97, 216}, {98, 65535, -37}, },
            {{0, 96, -25}, {97, 97, 217}, {98, 65535, -37}, },
            {{0, 12, -3}, {14, 102, 1}, {103, 103, 218}, {104, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 219}, {98, 65535, 1}, },
            {{0, 12, -3}, {14, 112, 1}, {113, 113, 220}, {114, 65535, 1}, },
            {{0, 109, -167}, {110, 110, 221}, {111, 65535, 1}, },
            {{0, 12, -3}, {14, 113, 1}, {114, 114, 222}, {115, 65535, 1}, },
            {{0, 12, -3}, {14, 110, 1}, {111, 111, 223}, {112, 65535, 1}, },
            {{0, 12, -3}, {14, 111, 1}, {112, 112, 224}, {113, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 113, -198}, {114, 114, 225}, {115, 65535, 1}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {{0, 110, -43}, {111, 111, 226}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 104, -74}, {105, 105, 227}, {106, 65535, -75}, },
            {{0, 108, -72}, {109, 109, 228}, {110, 65535, -72}, },
            {{0, 65535, -25}, },
            {{0, 100, -32}, {101, 101, 229}, {102, 65535, -32}, },
            {{0, 96, -50}, {97, 113, 50}, {114, 114, 230}, {115, 122, 50}, {123, 65535, 1}, },
            {{0, 100, -32}, {101, 101, 231}, {102, 65535, -32}, },
            {{0, 104, -74}, {105, 105, 232}, {106, 65535, -75}, },
            {{0, 108, -72}, {109, 109, 233}, {110, 65535, -72}, },
            {{0, 65535, -25}, },
            {{0, 113, -66}, {114, 114, 234}, {115, 65535, -39}, },
            {{0, 110, -43}, {111, 111, 235}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 107, -29}, {108, 108, 236}, {109, 65535, -71}, },
            {{0, 110, -199}, {111, 111, 237}, {112, 65535, 1}, },
            {{0, 107, -166}, {108, 108, 238}, {109, 65535, 1}, },
            {{0, 116, -168}, {117, 117, 239}, {118, 65535, 1}, },
            {{0, 12, -3}, {14, 98, 1}, {99, 99, 240}, {100, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 241}, {98, 65535, 1}, },
            {{0, 98, -223}, {99, 99, 242}, {100, 65535, 1}, },
            {{0, 12, -3}, {14, 104, 1}, {105, 105, 243}, {106, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 65535, -25}, },
            {{0, 108, -72}, {109, 109, 244}, {110, 65535, -72}, },
            {{0, 96, -25}, {97, 97, 245}, {98, 65535, -37}, },
            {{0, 65535, -25}, },
            {{0, 65535, -50}, },
            {{0, 104, -74}, {105, 105, 246}, {106, 65535, -75}, },
            {{0, 110, -43}, {111, 111, 247}, {112, 65535, -31}, },
            {{0, 110, -43}, {111, 111, 248}, {112, 65535, -31}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {{0, 113, -198}, {114, 114, 249}, {115, 65535, 1}, },
            {{0, 104, -226}, {105, 105, 250}, {106, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 251}, {98, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 252}, {98, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 100, -170}, {101, 101, 253}, {102, 65535, 1}, },
            {{0, 12, -3}, {14, 115, 1}, {116, 116, 254}, {117, 65535, 1}, },
            {{0, 100, -32}, {101, 101, 255}, {102, 65535, -32}, },
            {{0, 65535, -25}, },
            {{0, 113, -66}, {114, 114, 256}, {115, 65535, -39}, },
            {{0, 65535, -25}, },
            {{0, 65535, -25}, },
            {{0, 104, -226}, {105, 105, 257}, {106, 65535, 1}, },
            {{0, 100, -170}, {101, 101, 258}, {102, 65535, 1}, },
            {{0, 109, -167}, {110, 110, 259}, {111, 65535, 1}, },
            {{0, 110, -199}, {111, 111, 260}, {112, 65535, 1}, },
            {{0, 12, -3}, {14, 99, 1}, {100, 100, 261}, {101, 65535, 1}, },
            {{0, 96, -137}, {97, 97, 262}, {98, 65535, 1}, },
            {{0, 109, -33}, {110, 110, 263}, {111, 65535, -35}, },
            {{0, 110, -43}, {111, 111, 264}, {112, 65535, -31}, },
            {{0, 115, -245}, {116, 116, 265}, {117, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 115, -245}, {116, 116, 266}, {117, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 104, -226}, {105, 105, 267}, {106, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 115, -124}, {116, 116, 268}, {117, 65535, -69}, },
            {{0, 65535, -25}, },
            {{0, 12, -3}, {14, 108, 1}, {109, 109, 269}, {110, 65535, 1}, },
            {{0, 110, -199}, {111, 111, 270}, {112, 65535, 1}, },
            {{0, 108, -267}, {109, 109, 271}, {110, 65535, 1}, },
            {{0, 110, -43}, {111, 111, 272}, {112, 65535, -31}, },
            {{0, 110, -199}, {111, 111, 273}, {112, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 100, -170}, {101, 101, 274}, {102, 65535, 1}, },
            {{0, 65535, -25}, },
            {{0, 65535, -3}, },
            {{0, 109, -167}, {110, 110, 275}, {111, 65535, 1}, },
            {{0, 115, -245}, {116, 116, 276}, {117, 65535, 1}, },
            {{0, 110, -199}, {111, 111, 277}, {112, 65535, 1}, },
            {{0, 65535, -3}, },
        }
        { // COMMENT
            {{0, 9, 1}, {10, 10, 2}, {11, 12, 1}, {13, 13, 3}, {14, 41, 1}, {42, 42, 4}, {43, 46, 1}, {47, 47, 5}, {48, 65535, 1}, },
            {{0, 41, 1}, {43, 46, 1}, {48, 65535, 1}, },
            {{0, 65535, -3}, },
            {{0, 9, 1}, {10, 10, 6}, {11, 41, 1}, {43, 65535, -3}, },
            {{47, 47, 7}, },
            {{42, 42, 8}, },
            {{0, 65535, -3}, },
            {},
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {30, 30, 30, 70, 70, 30, 24, 30, 25, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 70, 0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 9, 30, 30, 30, 16, 30, 30, 30, 30, 77, 77, 30, 30, 30, 30, 26, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 8, 30, 30, 30, 30, 30, 30, 30, 30, 18, 30, 30, 20, 77, 30, 30, 30, 30, 30, 30, 29, 30, 30, 30, 30, 30, 3, 30, 30, 30, 30, 30, 30, 6, 30, 4, 30, 30, 30, 30, 13, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 17, 30, 30, 30, 30, 30, 27, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 5, 30, 7, 30, 30, 14, 30, 30, 30, 30, 30, 23, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 30, 30, 15, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 2, 30, 30, 30, 12, 30, 21, 22, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 19, 30, 30, 30, 30, 30, 30, 30, 11, 1, 30, 30, 30, 30, },
        // COMMENT
        {80, 80, 80, 80, 81, 82, 80, 79, 78, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMMENT = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
