/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorLFT.parser;

import compiladorLFT.node.*;
import compiladorLFT.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTDoisPontosFinais(@SuppressWarnings("unused") TDoisPontosFinais node)
    {
        this.index = 0;
    }

    @Override
    public void caseTFimAlgoritmo(@SuppressWarnings("unused") TFimAlgoritmo node)
    {
        this.index = 1;
    }

    @Override
    public void caseTFimPara(@SuppressWarnings("unused") TFimPara node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFaca(@SuppressWarnings("unused") TFaca node)
    {
        this.index = 3;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 4;
    }

    @Override
    public void caseTInicio(@SuppressWarnings("unused") TInicio node)
    {
        this.index = 5;
    }

    @Override
    public void caseTLeia(@SuppressWarnings("unused") TLeia node)
    {
        this.index = 6;
    }

    @Override
    public void caseTLogico(@SuppressWarnings("unused") TLogico node)
    {
        this.index = 7;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 8;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 9;
    }

    @Override
    public void caseTInteiro(@SuppressWarnings("unused") TInteiro node)
    {
        this.index = 10;
    }

    @Override
    public void caseTProcedimento(@SuppressWarnings("unused") TProcedimento node)
    {
        this.index = 11;
    }

    @Override
    public void caseTPrograma(@SuppressWarnings("unused") TPrograma node)
    {
        this.index = 12;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 13;
    }

    @Override
    public void caseTRepita(@SuppressWarnings("unused") TRepita node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRetorne(@SuppressWarnings("unused") TRetorne node)
    {
        this.index = 15;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 16;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 17;
    }

    @Override
    public void caseTVariavel(@SuppressWarnings("unused") TVariavel node)
    {
        this.index = 18;
    }

    @Override
    public void caseTVerdadeiro(@SuppressWarnings("unused") TVerdadeiro node)
    {
        this.index = 19;
    }

    @Override
    public void caseTXou(@SuppressWarnings("unused") TXou node)
    {
        this.index = 20;
    }

    @Override
    public void caseTAleatorio(@SuppressWarnings("unused") TAleatorio node)
    {
        this.index = 21;
    }

    @Override
    public void caseTAlgoritmo(@SuppressWarnings("unused") TAlgoritmo node)
    {
        this.index = 22;
    }

    @Override
    public void caseTArquivo(@SuppressWarnings("unused") TArquivo node)
    {
        this.index = 23;
    }

    @Override
    public void caseTAspasDuplas(@SuppressWarnings("unused") TAspasDuplas node)
    {
        this.index = 24;
    }

    @Override
    public void caseTAspasSimples(@SuppressWarnings("unused") TAspasSimples node)
    {
        this.index = 25;
    }

    @Override
    public void caseTAte(@SuppressWarnings("unused") TAte node)
    {
        this.index = 26;
    }

    @Override
    public void caseTAvalie(@SuppressWarnings("unused") TAvalie node)
    {
        this.index = 27;
    }

    @Override
    public void caseTCaracter(@SuppressWarnings("unused") TCaracter node)
    {
        this.index = 28;
    }

    @Override
    public void caseTCaso(@SuppressWarnings("unused") TCaso node)
    {
        this.index = 29;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 30;
    }

    @Override
    public void caseTColcheteD(@SuppressWarnings("unused") TColcheteD node)
    {
        this.index = 31;
    }

    @Override
    public void caseTColcheteE(@SuppressWarnings("unused") TColcheteE node)
    {
        this.index = 32;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 33;
    }

    @Override
    public void caseTDe(@SuppressWarnings("unused") TDe node)
    {
        this.index = 34;
    }

    @Override
    public void caseTDiferente(@SuppressWarnings("unused") TDiferente node)
    {
        this.index = 35;
    }

    @Override
    public void caseTDividido(@SuppressWarnings("unused") TDividido node)
    {
        this.index = 36;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 37;
    }

    @Override
    public void caseTE(@SuppressWarnings("unused") TE node)
    {
        this.index = 38;
    }

    @Override
    public void caseTEnquanto(@SuppressWarnings("unused") TEnquanto node)
    {
        this.index = 39;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 40;
    }

    @Override
    public void caseTEscolha(@SuppressWarnings("unused") TEscolha node)
    {
        this.index = 41;
    }

    @Override
    public void caseTEscreva(@SuppressWarnings("unused") TEscreva node)
    {
        this.index = 42;
    }

    @Override
    public void caseTEscreval(@SuppressWarnings("unused") TEscreval node)
    {
        this.index = 43;
    }

    @Override
    public void caseTFalso(@SuppressWarnings("unused") TFalso node)
    {
        this.index = 44;
    }

    @Override
    public void caseTFim(@SuppressWarnings("unused") TFim node)
    {
        this.index = 45;
    }

    @Override
    public void caseTFimEnquanto(@SuppressWarnings("unused") TFimEnquanto node)
    {
        this.index = 46;
    }

    @Override
    public void caseTFimFuncao(@SuppressWarnings("unused") TFimFuncao node)
    {
        this.index = 47;
    }

    @Override
    public void caseTFimProcedimento(@SuppressWarnings("unused") TFimProcedimento node)
    {
        this.index = 48;
    }

    @Override
    public void caseTFimRepita(@SuppressWarnings("unused") TFimRepita node)
    {
        this.index = 49;
    }

    @Override
    public void caseTFimSe(@SuppressWarnings("unused") TFimSe node)
    {
        this.index = 50;
    }

    @Override
    public void caseTFimVar(@SuppressWarnings("unused") TFimVar node)
    {
        this.index = 51;
    }

    @Override
    public void caseTFimAvalie(@SuppressWarnings("unused") TFimAvalie node)
    {
        this.index = 52;
    }

    @Override
    public void caseTFuncao(@SuppressWarnings("unused") TFuncao node)
    {
        this.index = 53;
    }

    @Override
    public void caseTIdentificador(@SuppressWarnings("unused") TIdentificador node)
    {
        this.index = 54;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 55;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 56;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 57;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 58;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 59;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 60;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 61;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 62;
    }

    @Override
    public void caseTParenteseD(@SuppressWarnings("unused") TParenteseD node)
    {
        this.index = 63;
    }

    @Override
    public void caseTParenteseE(@SuppressWarnings("unused") TParenteseE node)
    {
        this.index = 64;
    }

    @Override
    public void caseTPasso(@SuppressWarnings("unused") TPasso node)
    {
        this.index = 65;
    }

    @Override
    public void caseTPausa(@SuppressWarnings("unused") TPausa node)
    {
        this.index = 66;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 67;
    }

    @Override
    public void caseTRecebe(@SuppressWarnings("unused") TRecebe node)
    {
        this.index = 68;
    }

    @Override
    public void caseTResto(@SuppressWarnings("unused") TResto node)
    {
        this.index = 69;
    }

    @Override
    public void caseTVezes(@SuppressWarnings("unused") TVezes node)
    {
        this.index = 70;
    }

    @Override
    public void caseTNumeroInt(@SuppressWarnings("unused") TNumeroInt node)
    {
        this.index = 71;
    }

    @Override
    public void caseTNumeroReal(@SuppressWarnings("unused") TNumeroReal node)
    {
        this.index = 72;
    }

    @Override
    public void caseTVarStr(@SuppressWarnings("unused") TVarStr node)
    {
        this.index = 73;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 74;
    }

    @Override
    public void caseTXor(@SuppressWarnings("unused") TXor node)
    {
        this.index = 75;
    }

    @Override
    public void caseTComentarioSimples(@SuppressWarnings("unused") TComentarioSimples node)
    {
        this.index = 76;
    }

    @Override
    public void caseTCommentEnd(@SuppressWarnings("unused") TCommentEnd node)
    {
        this.index = 77;
    }

    @Override
    public void caseTCommentBody(@SuppressWarnings("unused") TCommentBody node)
    {
        this.index = 78;
    }

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 79;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 80;
    }

    @Override
    public void caseTFimTexto(@SuppressWarnings("unused") TFimTexto node)
    {
        this.index = 81;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 82;
    }
}
